### ISSUE TITLE
Cardano API not found

### ISSUE THREAD

**Issue by rgouzal** [Emurgo/dapp-connector-web#1]
I tried to visit https://dapp-connector-web.emurgo-rnd.com/ to see if it is working, it appears that it returns error stating:

> Cardano API not found

I  already have Yoroi wallet installed in Mozilla browser.

**Comment by neuodev** [comment]
Hi, @rgouzal! Thanks for submitting the first issue! 
Can you please give more context? For example the Yoroi Version! the logs in the console and the browser version?

**Comment by rgouzal** [comment]
@AhmedIbrahim336 Hello Sir, thank for replying. I figured that I had the wrong version of Yoroi extension that did not have dApp feature added, I managed to get it working. Sorry for any inconvenience.

**Comment by neuodev** [comment]
No problem!
